language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghc802
    - env: GHCVER=ghc822
    - env: GHCVER=ghc842
    - env: GHCVER=ghcHEAD
  allow_failures:
    - env: GHCVER=ghc802
    - env: GHCVER=ghc842
    - env: GHCVER=ghcHEAD

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build -A stripe-haskell --argstr compiler $GHCVER --arg check true
